2019-07-07 12:31:29,266 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 14:20:46,370 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 14:20:53,223 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 14:42:05,303 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 14:44:21,643 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 15:41:37,114 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 15:42:37,706 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 15:51:04,591 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 16:03:26,604 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 16:10:32,758 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 16:10:39,446 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 16:13:15,949 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 16:21:58,795 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 16:22:38,202 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 16:24:10,681 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 16:25:32,256 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 16:26:54,331 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 16:27:37,571 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 16:46:02,296 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 16:55:08,565 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 16:56:09,009 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 17:01:22,780 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 17:02:22,068 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 17:05:34,184 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 17:06:21,099 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 17:25:51,635 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 17:40:21,636 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 17:46:56,614 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 18:00:17,016 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 18:14:04,736 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 18:14:19,464 ERROR: Exception on /login [POST] [in /home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lomolo/Projects/microblog/app/routes.py", line 56, in login
    user=User.query.filter_by(username=form.username.data).first()
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3222, in first
    ret = list(self[0:1])
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3012, in __getitem__
    return list(res)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3324, in __iter__
    return self._execute_and_instances(context)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3349, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 399, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such table: user
[SQL: SELECT user.id AS user_id, user.username AS user_username, user.email AS user_email, user.password_hash AS user_password_hash, user.about_me AS user_about_me, user.last_seen AS user_last_seen 
FROM user 
WHERE user.username = ?
 LIMIT ? OFFSET ?]
[parameters: (u'username', 1, 0)]
(Background on this error at: http://sqlalche.me/e/e3q8)
